Approved App Listing (updated)
remotestorage/armadietto pull request #108
Opened 2023-12-29 23:09 UTC by silverbucket

I've taken @AngeloR's PR (https://github.com/remotestorage/armadietto/pull/47) and updated it with the improved styling, resolved some conflicts, but otherwise left it as-is.

The PR looks good to me, and the only comment from @raucao was that we add a revoke button as part of the app listing. A quick look through the code and it looks like there is no API functionality to do this yet, so I think it's out of scope of this PR. We can create an issue to implement that. 

Aside from any other issues I overlooked, I propose we go ahead and merged this.

2024-01-02 00:12 UTC, DougReeder requested changes
For my dev server, the app listing looks like this:
![Screenshot 2024-01-01 at 6 47 46 PM](https://github.com/remotestorage/armadietto/assets/378430/5192cf25-14f0-41cd-a05b-cd0c6d528826)

1. Inspektor appears twice. Is that a bug in this PR, or somewhere else?
2. All of the favicons are blocked by our Content Security Policy. To allow them, we'd have to allow images from **any** site.  I don't think the value is worth the risk.
3. Not all apps store their favicon at this location, so we'd miss some available favicons

I think we should drop the favicons entirely.

2024-01-02 00:12 UTC, DougReeder commented on lib/controllers/users.js
> +      this.renderHTML(409, 'login.html', { params: this.params, error });
Can we verify that a caught error will result in a reasonable message to the user, and a useful message in the log?

2024-01-04 14:52 UTC, DougReeder commented
This list just shows what's in `auth.json`, so the duplicate of inspektor is not a bug in this PR.

2024-01-04 15:41 UTC, DougReeder commented
The error message is as good as we can do, until #106 is merged.

2024-01-04 15:41 UTC, DougReeder commented on lib/controllers/users.js
> +      this.renderHTML(409, 'login.html', { params: this.params, error });
The error message is as good as we can do, until https://github.com/remotestorage/armadietto/pull/106 is merged.

2024-01-04 16:05 UTC, silverbucket commented
> I think we should drop the favicons entirely.

@DougReeder  Agreed, I've removed them. Tests are passing, so with your approval I'll merge.

2024-01-04 17:50 UTC, DougReeder approved these changes

2024-01-04 17:51 UTC, DougReeder commented
We're good to merge!

2024-01-04 18:36 UTC, merged